apiVersion: skaffold/v1beta2
kind: Config
build:
  local: # this means don't push to your git repo
    push: false # when the setting is set to false.
  artifacts:
    - image: rwuniard/react-kube
      context: client
      docker:
        dockerfile: Dockerfile.dev
      sync:
        "**/*.js": . # This means detect any javascript changes and copy it to target in kubernetes
        "**/*.css": .
        "**/*.html": .
deploy:
  kubectl:
    manifests:
      - k8s/client-deployment.yaml
      - k8s/client-node-port.yaml
#      - k8s/client-cluster-ip-service.yaml
#      - k8s/ingress-service.yaml
